name: autorun

on:
  workflow_dispatch:
  schedule:
    # 每小时执行一次，从 UTC 的22:00到23:00（北京时间第二天早上6:00到7:00）
    - cron: '0 22-23 * * *'
    # 每小时执行一次，从 UTC 的0:00到18:00（北京时间早上8:00到次日凌晨2:00）
    - cron: '0 0-18 * * *'

jobs:
  ssh-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run script on remote server
      run: ssh -o StrictHostKeyChecking=no ptputata@s8.serv00.com "./run.sh"
      # ktech@s4.serv00.com这里换成自己的服务器名字
